import { Router, Request, Response } from 'express';
import pool from '../lib/db';

const router = Router();

// ---- Helpers ----

async function ensureServicesTable() {
  const client = await pool.connect();
  try {
    const r = await client.query(
      `SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='services') AS exists`,
    );
    if (!r.rows[0].exists) {
      await client.query(`
        CREATE TABLE services (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL, value NUMERIC(10,2) NOT NULL, description TEXT,
          created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
          updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL
        )
      `);
      return;
    }
    await client.query(`ALTER TABLE services ADD COLUMN IF NOT EXISTS name TEXT`);
    await client.query(`ALTER TABLE services ADD COLUMN IF NOT EXISTS value NUMERIC(10,2)`);
    await client.query(`ALTER TABLE services ADD COLUMN IF NOT EXISTS description TEXT`);
    await client.query(`ALTER TABLE services ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE`);
    await client.query(`ALTER TABLE services ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE`);
    await client.query(`ALTER TABLE services ALTER COLUMN created_at SET DEFAULT NOW()`);
    await client.query(`ALTER TABLE services ALTER COLUMN updated_at SET DEFAULT NOW()`);
  } finally {
    client.release();
  }
}

async function getServiceColumns() {
  const client = await pool.connect();
  try {
    const res = await client.query(
      `SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name='services'`,
    );
    const cols = res.rows.map((r) => String(r.column_name));
    return {
      nameCol: cols.includes('nome') ? 'nome' : 'name',
      valueCol: cols.includes('valor') ? 'valor' : 'value',
      descriptionCol: cols.includes('descricao') ? 'descricao' : 'description',
    };
  } finally {
    client.release();
  }
}

async function seedIfEmpty(nameCol: string, valueCol: string, descriptionCol: string) {
  const client = await pool.connect();
  try {
    const res = await client.query('SELECT COUNT(*) FROM services');
    if (parseInt(res.rows[0].count) > 0) return;
    await client.query(
      `INSERT INTO services (${nameCol},${valueCol},${descriptionCol}) VALUES
       ($1,$2,$3),($4,$5,$6),($7,$8,$9),($10,$11,$12),($13,$14,$15)`,
      [
        'Abertura de MEI', 0, 'Processo completo de abertura de Microempreendedor Individual',
        'Regularização de Pendências', 0, 'Análise e regularização de pendências fiscais do MEI',
        'Declaração Anual (DASN-SIMEI)', 0, 'Envio da declaração anual de faturamento do MEI',
        'Parcelamento de Dívidas', 0, 'Negociação e parcelamento de dívidas fiscais',
        'Consultoria Contábil', 0, 'Orientação contábil especializada para MEI e empresas',
      ],
    );
  } catch (e) {
    console.error('[Services] Seed error:', e);
  } finally {
    client.release();
  }
}

// GET /services
router.get('/services', async (_req: Request, res: Response) => {
  try {
    await ensureServicesTable();
    const { nameCol, valueCol, descriptionCol } = await getServiceColumns();
    await seedIfEmpty(nameCol, valueCol, descriptionCol);
    const result = await pool.query(
      `SELECT id, ${nameCol} AS name, ${valueCol} AS value, ${descriptionCol} AS description, created_at, updated_at FROM services ORDER BY id ASC`,
    );
    res.json(result.rows);
  } catch (err) {
    console.error('Erro ao listar serviços:', err);
    res.status(500).json({ error: 'Erro ao listar serviços' });
  }
});

// POST /services
router.post('/services', async (req: Request, res: Response) => {
  try {
    await ensureServicesTable();
    const { nameCol, valueCol, descriptionCol } = await getServiceColumns();
    await seedIfEmpty(nameCol, valueCol, descriptionCol);
    const { name, value, description } = req.body;
    if (!name || value === undefined) return void res.status(400).json({ error: 'Nome e valor são obrigatórios' });
    const result = await pool.query(
      `INSERT INTO services (${nameCol},${valueCol},${descriptionCol}) VALUES ($1,$2,$3)
       RETURNING id, ${nameCol} AS name, ${valueCol} AS value, ${descriptionCol} AS description, created_at, updated_at`,
      [name, value, description || ''],
    );
    res.json(result.rows[0]);
  } catch (err) {
    console.error('Erro ao criar serviço:', err);
    res.status(500).json({ error: 'Erro ao criar serviço' });
  }
});

// PUT /services/:id
router.put('/services/:id', async (req: Request, res: Response) => {
  try {
    await ensureServicesTable();
    const { nameCol, valueCol, descriptionCol } = await getServiceColumns();
    const { id } = req.params;
    const { name, value, description } = req.body;
    const setParts: string[] = [];
    const values: unknown[] = [];
    let idx = 1;
    if (typeof name === 'string' && name.length > 0) { setParts.push(`${nameCol} = $${idx++}`); values.push(name); }
    if (value !== undefined && !Number.isNaN(Number(value))) { setParts.push(`${valueCol} = $${idx++}`); values.push(Number(value)); }
    if (typeof description === 'string') { setParts.push(`${descriptionCol} = $${idx++}`); values.push(description); }
    setParts.push('updated_at = NOW()');
    values.push(id);
    const sql = `UPDATE services SET ${setParts.join(', ')} WHERE id = $${idx} RETURNING id, ${nameCol} AS name, ${valueCol} AS value, ${descriptionCol} AS description, created_at, updated_at`;
    const result = await pool.query(sql, values);
    if (result.rowCount === 0) return void res.status(404).json({ error: 'Serviço não encontrado' });
    res.json(result.rows[0]);
  } catch (err) {
    console.error('Erro ao atualizar serviço:', err);
    res.status(500).json({ error: 'Erro ao atualizar serviço' });
  }
});

// DELETE /services/:id
router.delete('/services/:id', async (req: Request, res: Response) => {
  try {
    await ensureServicesTable();
    const result = await pool.query('DELETE FROM services WHERE id = $1', [req.params.id]);
    if (result.rowCount === 0) return void res.status(404).json({ error: 'Serviço não encontrado' });
    res.json({ success: true });
  } catch (err) {
    console.error('Erro ao excluir serviço:', err);
    res.status(500).json({ error: 'Erro ao excluir serviço' });
  }
});

export default router;
